language: python
python:
  - "3.11"  # or your project's Python version
services:
  - postgresql  # or any database your project uses
addons:
  postgresql: "12"
before_script:
  - psql -c 'create database myapp;' -U postgres
  - python manage.py migrate  # adjust according to your database setup
install:
  - pip install -r requirements.txt
  - pip install flake8 black coverage coveralls
script:
  - black --check .  # Check code formatting
  - flake8 .  # Linting
  - coverage run manage.py test  # Run tests
after_success:
  - coveralls  # Report coverage
before_deploy: "echo 'ready?'"
deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env-3"
  bucket_name: "elasticbeanstalk-us-west-2-985539801738"
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
  on:
    branch: main
