language: python

install:
  - pip install -r requirements.txt
  - pip install flake8 black coverage coveralls

script:
  - black --check .
  - flake8 --max-line-length=500 .
  - coverage run manage.py test

after_success:
  - coveralls

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "django-tutorial"
  env: "django-env-3"
  bucket_name: "elasticbeanstalk-us-west-2-985539801738"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: main